basePath: /api
definitions:
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact:
    email: blackhorseya@gmail.com
    name: Sean Zheng
    url: https://blog.seancheng.space
  title: Orianna API
  version: 0.1.0
paths:
  /healthz:
    get:
      consumes:
      - application/json
      description: Check the health of the service.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: healthz
      tags:
      - healthz
  /v1/stats/info:
    get:
      consumes:
      - application/json
      description: Get Stats
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get Stats
      tags:
      - stats
  /v1/stocks:
    get:
      consumes:
      - application/json
      description: Get a list of stocks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: List stocks
      tags:
      - stocks
  /v1/stocks/{symbol}:
    get:
      consumes:
      - application/json
      description: get stock by symbol
      parameters:
      - description: Stock symbol
        in: path
        name: symbol
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get stock by symbol
      tags:
      - stocks
swagger: "2.0"
