// Code generated by MockGen. DO NOT EDIT.
// Source: asset.go

// Package repo is a generated GoMock package.
package repo

import (
	reflect "reflect"

	agg "github.com/blackhorseya/monorepo-go/entity/sion/domain/rental/agg"
	contextx "github.com/blackhorseya/monorepo-go/pkg/contextx"
	gomock "go.uber.org/mock/gomock"
)

// MockIAssetRepo is a mock of IAssetRepo interface.
type MockIAssetRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIAssetRepoMockRecorder
}

// MockIAssetRepoMockRecorder is the mock recorder for MockIAssetRepo.
type MockIAssetRepoMockRecorder struct {
	mock *MockIAssetRepo
}

// NewMockIAssetRepo creates a new mock instance.
func NewMockIAssetRepo(ctrl *gomock.Controller) *MockIAssetRepo {
	mock := &MockIAssetRepo{ctrl: ctrl}
	mock.recorder = &MockIAssetRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAssetRepo) EXPECT() *MockIAssetRepoMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockIAssetRepo) List(ctx contextx.Contextx, opts ListOptions) ([]*agg.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].([]*agg.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIAssetRepoMockRecorder) List(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIAssetRepo)(nil).List), ctx, opts)
}
