// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package restful

import (
	"github.com/blackhorseya/monorepo-go/app/domain/shortening/biz"
	"github.com/blackhorseya/monorepo-go/app/domain/shortening/repo/memory"
	redis2 "github.com/blackhorseya/monorepo-go/app/domain/shortening/repo/redis"
	"github.com/blackhorseya/monorepo-go/pkg/adapterx"
	"github.com/blackhorseya/monorepo-go/pkg/storage/redis"
	"github.com/spf13/viper"
)

import (
	_ "github.com/blackhorseya/monorepo-go/adapter/shortenurl/api/docs"
)

// Injectors from wire.go:

func New(v *viper.Viper) (adapterx.Servicer, error) {
	storager := memory.NewStorager()
	iShorteningBiz := biz.NewShortening(storager)
	servicer, err := newRestful(iShorteningBiz)
	if err != nil {
		return nil, err
	}
	return servicer, nil
}

func NewWithRedis(v *viper.Viper) (adapterx.Servicer, error) {
	client, err := redis.NewClient()
	if err != nil {
		return nil, err
	}
	storager, err := redis2.NewStorager(client)
	if err != nil {
		return nil, err
	}
	iShorteningBiz := biz.NewShortening(storager)
	servicer, err := newRestful(iShorteningBiz)
	if err != nil {
		return nil, err
	}
	return servicer, nil
}
