// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.25.1
// source: entity/domain/stringx/model/stringx.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ToUpperRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ToUpperRequest) Reset() {
	*x = ToUpperRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_domain_stringx_model_stringx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToUpperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToUpperRequest) ProtoMessage() {}

func (x *ToUpperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_domain_stringx_model_stringx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToUpperRequest.ProtoReflect.Descriptor instead.
func (*ToUpperRequest) Descriptor() ([]byte, []int) {
	return file_entity_domain_stringx_model_stringx_proto_rawDescGZIP(), []int{0}
}

func (x *ToUpperRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ToUpperResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ToUpperResponse) Reset() {
	*x = ToUpperResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_domain_stringx_model_stringx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToUpperResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToUpperResponse) ProtoMessage() {}

func (x *ToUpperResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entity_domain_stringx_model_stringx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToUpperResponse.ProtoReflect.Descriptor instead.
func (*ToUpperResponse) Descriptor() ([]byte, []int) {
	return file_entity_domain_stringx_model_stringx_proto_rawDescGZIP(), []int{1}
}

func (x *ToUpperResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *CountRequest) Reset() {
	*x = CountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_domain_stringx_model_stringx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRequest) ProtoMessage() {}

func (x *CountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_domain_stringx_model_stringx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRequest.ProtoReflect.Descriptor instead.
func (*CountRequest) Descriptor() ([]byte, []int) {
	return file_entity_domain_stringx_model_stringx_proto_rawDescGZIP(), []int{2}
}

func (x *CountRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *CountResponse) Reset() {
	*x = CountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_domain_stringx_model_stringx_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResponse) ProtoMessage() {}

func (x *CountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entity_domain_stringx_model_stringx_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResponse.ProtoReflect.Descriptor instead.
func (*CountResponse) Descriptor() ([]byte, []int) {
	return file_entity_domain_stringx_model_stringx_proto_rawDescGZIP(), []int{3}
}

func (x *CountResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_entity_domain_stringx_model_stringx_proto protoreflect.FileDescriptor

var file_entity_domain_stringx_model_stringx_proto_rawDesc = []byte{
	0x0a, 0x29, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x78, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x78, 0x22, 0x26, 0x0a, 0x0e, 0x54, 0x6f, 0x55, 0x70, 0x70, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x27, 0x0a, 0x0f,
	0x54, 0x6f, 0x55, 0x70, 0x70, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x24, 0x0a, 0x0c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x25, 0x0a, 0x0d, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x32, 0x8a, 0x01, 0x0a, 0x0e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x78, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x07, 0x54, 0x6f, 0x55, 0x70, 0x70, 0x65, 0x72,
	0x12, 0x17, 0x2e, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x78, 0x2e, 0x54, 0x6f, 0x55, 0x70, 0x70,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x78, 0x2e, 0x54, 0x6f, 0x55, 0x70, 0x70, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x15,
	0x2e, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x78, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x78, 0x2e,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6c,
	0x61, 0x63, 0x6b, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x79, 0x61, 0x2f, 0x6d, 0x6f, 0x6e, 0x6f, 0x72,
	0x65, 0x70, 0x6f, 0x2d, 0x67, 0x6f, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x78, 0x2f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entity_domain_stringx_model_stringx_proto_rawDescOnce sync.Once
	file_entity_domain_stringx_model_stringx_proto_rawDescData = file_entity_domain_stringx_model_stringx_proto_rawDesc
)

func file_entity_domain_stringx_model_stringx_proto_rawDescGZIP() []byte {
	file_entity_domain_stringx_model_stringx_proto_rawDescOnce.Do(func() {
		file_entity_domain_stringx_model_stringx_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_domain_stringx_model_stringx_proto_rawDescData)
	})
	return file_entity_domain_stringx_model_stringx_proto_rawDescData
}

var file_entity_domain_stringx_model_stringx_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_entity_domain_stringx_model_stringx_proto_goTypes = []interface{}{
	(*ToUpperRequest)(nil),  // 0: stringx.ToUpperRequest
	(*ToUpperResponse)(nil), // 1: stringx.ToUpperResponse
	(*CountRequest)(nil),    // 2: stringx.CountRequest
	(*CountResponse)(nil),   // 3: stringx.CountResponse
}
var file_entity_domain_stringx_model_stringx_proto_depIdxs = []int32{
	0, // 0: stringx.StringxService.ToUpper:input_type -> stringx.ToUpperRequest
	2, // 1: stringx.StringxService.Count:input_type -> stringx.CountRequest
	1, // 2: stringx.StringxService.ToUpper:output_type -> stringx.ToUpperResponse
	3, // 3: stringx.StringxService.Count:output_type -> stringx.CountResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_domain_stringx_model_stringx_proto_init() }
func file_entity_domain_stringx_model_stringx_proto_init() {
	if File_entity_domain_stringx_model_stringx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_domain_stringx_model_stringx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToUpperRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_domain_stringx_model_stringx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToUpperResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_domain_stringx_model_stringx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_domain_stringx_model_stringx_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_domain_stringx_model_stringx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_entity_domain_stringx_model_stringx_proto_goTypes,
		DependencyIndexes: file_entity_domain_stringx_model_stringx_proto_depIdxs,
		MessageInfos:      file_entity_domain_stringx_model_stringx_proto_msgTypes,
	}.Build()
	File_entity_domain_stringx_model_stringx_proto = out.File
	file_entity_domain_stringx_model_stringx_proto_rawDesc = nil
	file_entity_domain_stringx_model_stringx_proto_goTypes = nil
	file_entity_domain_stringx_model_stringx_proto_depIdxs = nil
}
