// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package biz is a generated GoMock package.
package biz

import (
	gomock "go.uber.org/mock/gomock"
)

// MockIUserBiz is a mock of IUserBiz interface.
type MockIUserBiz struct {
	ctrl     *gomock.Controller
	recorder *MockIUserBizMockRecorder
}

// MockIUserBizMockRecorder is the mock recorder for MockIUserBiz.
type MockIUserBizMockRecorder struct {
	mock *MockIUserBiz
}

// NewMockIUserBiz creates a new mock instance.
func NewMockIUserBiz(ctrl *gomock.Controller) *MockIUserBiz {
	mock := &MockIUserBiz{ctrl: ctrl}
	mock.recorder = &MockIUserBizMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserBiz) EXPECT() *MockIUserBizMockRecorder {
	return m.recorder
}
