// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package biz is a generated GoMock package.
package biz

import (
	reflect "reflect"

	model "github.com/blackhorseya/monorepo-go/entity/domain/shortening/model"
	contextx "github.com/blackhorseya/monorepo-go/pkg/contextx"
	gomock "go.uber.org/mock/gomock"
)

// MockIShorteningBiz is a mock of IShorteningBiz interface.
type MockIShorteningBiz struct {
	ctrl     *gomock.Controller
	recorder *MockIShorteningBizMockRecorder
}

// MockIShorteningBizMockRecorder is the mock recorder for MockIShorteningBiz.
type MockIShorteningBizMockRecorder struct {
	mock *MockIShorteningBiz
}

// NewMockIShorteningBiz creates a new mock instance.
func NewMockIShorteningBiz(ctrl *gomock.Controller) *MockIShorteningBiz {
	mock := &MockIShorteningBiz{ctrl: ctrl}
	mock.recorder = &MockIShorteningBizMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIShorteningBiz) EXPECT() *MockIShorteningBizMockRecorder {
	return m.recorder
}

// GetUrlRecordByShortUrl mocks base method.
func (m *MockIShorteningBiz) GetUrlRecordByShortUrl(ctx contextx.Contextx, shortUrl string) (*model.ShortenedUrl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUrlRecordByShortUrl", ctx, shortUrl)
	ret0, _ := ret[0].(*model.ShortenedUrl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUrlRecordByShortUrl indicates an expected call of GetUrlRecordByShortUrl.
func (mr *MockIShorteningBizMockRecorder) GetUrlRecordByShortUrl(ctx, shortUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUrlRecordByShortUrl", reflect.TypeOf((*MockIShorteningBiz)(nil).GetUrlRecordByShortUrl), ctx, shortUrl)
}
