service: reurl

frameworkVersion: '3'
configValidationMode: error

plugins:
  - serverless-go-plugin
  - serverless-offline

custom:
  go:
    baseDir: . # folder where go.mod file lives, if set `handler` property should be set relatively to that folder
    binDir: bin # target folder for binary files
    supportedRuntimes: [ "provided.al2" ] # the plugin compiles a function only if runtime is declared here (either on function or provider level)
    buildProvidedRuntimeAsBootstrap: true # if enabled, builds and archive function with only single "bootstrap" binary (useful for runtimes like provided.al2)
  serverless-offline:
    httpPort: 1992
    host: 0.0.0.0
    useDocker: true

provider:
  name: aws
  runtime: provided.al2
  stage: ${opt:stage, 'prod'}
  region: ap-northeast-3
  timeout: 29

package:
  individually: true

functions:
  restful:
    handler: ./cmd/restful
    events:
      - http:
          path: /callback
          method: POST
