service: reurl

plugins:
  - serverless-go-plugin

custom:
  go:
    baseDir: . # folder where go.mod file lives, if set `handler` property should be set relatively to that folder
    binDir: bin # target folder for binary files
    cgo: 0 # CGO_ENABLED flag
    cmd: 'GOARCH=amd64 GOOS=linux go build -ldflags="-s -w"' # compile command
    monorepo: false # if enabled, builds function every directory (useful for monorepo where go.mod is managed by each function
    supportedRuntimes: [ "go1.x" ] # the plugin compiles a function only if runtime is declared here (either on function or provider level)
    buildProvidedRuntimeAsBootstrap: false # if enabled, builds and archive function with only single "bootstrap" binary (useful for runtimes like provided.al2)

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'prod'}
  region: ap-northeast-3
  timeout: 29

package:
  individually: true

functions:
  restful:
    handler: ./cmd/restful
    events:
      - httpApi:
          path: /
          method: '*'
