// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	mongodb2 "github.com/blackhorseya/monorepo-go/app/orianna/domain/market/repo/stock/mongodb"
	"github.com/blackhorseya/monorepo-go/entity/orianna/domain/market/repo"
	"github.com/blackhorseya/monorepo-go/pkg/notify"
	"github.com/blackhorseya/monorepo-go/pkg/storage/mongodb"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, error) {
	client, err := mongodb.NewClient()
	if err != nil {
		return nil, err
	}
	notifier, err := notify.NewLineNotifier()
	if err != nil {
		return nil, err
	}
	iStockRepo, err := mongodb2.NewStockRepo(client)
	if err != nil {
		return nil, err
	}
	injector := &Injector{
		rw:       client,
		notifier: notifier,
		repo:     iStockRepo,
	}
	return injector, nil
}

// wire.go:

// Injector is the injector for main.
type Injector struct {
	rw       *mongo.Client
	notifier notify.Notifier
	repo     repo.IStockRepo
}
