// Code generated by MockGen. DO NOT EDIT.
// Source: dialer.go

// Package client is a generated GoMock package.
package restful

import (
	reflect "reflect"

	agg "github.com/blackhorseya/monorepo-go/entity/orianna/domain/market/agg"
	contextx "github.com/blackhorseya/monorepo-go/pkg/contextx"
	gomock "go.uber.org/mock/gomock"
)

// MockDialer is a mock of Dialer interface.
type MockDialer struct {
	ctrl     *gomock.Controller
	recorder *MockDialerMockRecorder
}

// MockDialerMockRecorder is the mock recorder for MockDialer.
type MockDialerMockRecorder struct {
	mock *MockDialer
}

// NewMockDialer creates a new mock instance.
func NewMockDialer(ctrl *gomock.Controller) *MockDialer {
	mock := &MockDialer{ctrl: ctrl}
	mock.recorder = &MockDialerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDialer) EXPECT() *MockDialerMockRecorder {
	return m.recorder
}

// GetStockBySymbol mocks base method.
func (m *MockDialer) GetStockBySymbol(ctx contextx.Contextx, symbol string) (agg.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockBySymbol", ctx, symbol)
	ret0, _ := ret[0].(agg.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockBySymbol indicates an expected call of GetStockBySymbol.
func (mr *MockDialerMockRecorder) GetStockBySymbol(ctx, symbol interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockBySymbol", reflect.TypeOf((*MockDialer)(nil).GetStockBySymbol), ctx, symbol)
}
