basePath: /api
definitions:
  endpoints.CreateRedPacketRequest:
    properties:
      amount:
        type: integer
      count:
        type: integer
      who:
        $ref: '#/definitions/model.UserAccount'
    type: object
  endpoints.CreateRedPacketResponse:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  endpoints.ListRedPacketResponse:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  model.Profile:
    properties:
      first_name:
        type: string
      last_name:
        type: string
    type: object
  model.UserAccount:
    properties:
      access_token:
        type: string
      email:
        type: string
      id:
        type: string
      id_token:
        type: string
      password:
        description: 'gotags: json="-"'
        type: string
      profile:
        $ref: '#/definitions/model.Profile'
      username:
        type: string
    type: object
info:
  contact:
    email: blackhorseya@gmail.com
    name: Sean Zheng
    url: https://blog.seancheng.space
  description: This is a sample server for redpacket.
  title: RedPacket API
  version: 0.1.0
paths:
  /v1/redpackets:
    get:
      consumes:
      - application/json
      description: list red packet
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/endpoints.ListRedPacketResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/endpoints.ListRedPacketResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/endpoints.ListRedPacketResponse'
      summary: list red packet
      tags:
      - RedPacket
    post:
      consumes:
      - application/json
      description: create red packet
      parameters:
      - description: create red packet request
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/endpoints.CreateRedPacketRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/endpoints.CreateRedPacketResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/endpoints.CreateRedPacketResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/endpoints.CreateRedPacketResponse'
      summary: create red packet
      tags:
      - RedPacket
swagger: "2.0"
