// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package restful

import (
	"github.com/blackhorseya/monorepo-go/internal/app/domain/event/biz"
	"github.com/blackhorseya/monorepo-go/internal/app/domain/event/repo/memory"
	"github.com/blackhorseya/monorepo-go/internal/pkg/configx"
	"github.com/blackhorseya/monorepo-go/internal/pkg/logx"
	"github.com/blackhorseya/monorepo-go/pkg/adapterx"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

import (
	_ "github.com/blackhorseya/monorepo-go/adapter/redpacket/api/docs"
)

// Injectors from wire.go:

func New(v *viper.Viper) (adapterx.Servicer, error) {
	config, err := configx.NewWithViper(v)
	if err != nil {
		return nil, err
	}
	logger, err := logx.NewWithConfig(config)
	if err != nil {
		return nil, err
	}
	storager := memory.New()
	iEventBiz := biz.New(storager)
	servicer := newImpl(config, logger, iEventBiz)
	return servicer, nil
}

// wire.go:

var providerSet = wire.NewSet(configx.NewWithViper, logx.NewWithConfig, newImpl, biz.New, memory.New)
