// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package biz is a generated GoMock package.
package biz

import (
	gomock "go.uber.org/mock/gomock"
)

// MockIMarketBiz is a mock of IMarketBiz interface.
type MockIMarketBiz struct {
	ctrl     *gomock.Controller
	recorder *MockIMarketBizMockRecorder
}

// MockIMarketBizMockRecorder is the mock recorder for MockIMarketBiz.
type MockIMarketBizMockRecorder struct {
	mock *MockIMarketBiz
}

// NewMockIMarketBiz creates a new mock instance.
func NewMockIMarketBiz(ctrl *gomock.Controller) *MockIMarketBiz {
	mock := &MockIMarketBiz{ctrl: ctrl}
	mock.recorder = &MockIMarketBizMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMarketBiz) EXPECT() *MockIMarketBizMockRecorder {
	return m.recorder
}
