// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/blackhorseya/monorepo-go/pkg/finmindx"
	"github.com/blackhorseya/monorepo-go/pkg/notify"
	"github.com/blackhorseya/monorepo-go/pkg/storage/mongodb"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, error) {
	dialer, err := finmindx.NewClient()
	if err != nil {
		return nil, err
	}
	client, err := mongodb.NewClient()
	if err != nil {
		return nil, err
	}
	notifyNotifier, err := notify.NewLineNotifier()
	if err != nil {
		return nil, err
	}
	injector := &Injector{
		finmind:  dialer,
		rw:       client,
		notifier: notifyNotifier,
	}
	return injector, nil
}

// wire.go:

// Injector is the injector for main.
type Injector struct {
	finmind  finmindx.Dialer
	rw       *mongo.Client
	notifier notify.Notifier
}
