// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package biz

import (
	mongodb2 "github.com/blackhorseya/monorepo-go/app/orianna1/domain/market/repo/mongodb"
	"github.com/blackhorseya/monorepo-go/entity/orianna/domain/market/biz"
	"github.com/blackhorseya/monorepo-go/pkg/storage/mongodb"
	"github.com/google/wire"
)

// Injectors from wire.go:

func newForTest() (biz.IMarketBiz, error) {
	client, err := mongodb.NewClient()
	if err != nil {
		return nil, err
	}
	iStockRepo, err := mongodb2.NewStockRepo(client)
	if err != nil {
		return nil, err
	}
	iMarketBiz, err := NewMarketBiz(iStockRepo)
	if err != nil {
		return nil, err
	}
	return iMarketBiz, nil
}

// wire.go:

var ProviderSet = wire.NewSet(
	NewMarketBiz, mongodb2.NewStockRepo,
)
