// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cronjob

import (
	"github.com/blackhorseya/monorepo-go/pkg/adapterx"
	"github.com/google/wire"
)

// Injectors from wire.go:

// New will create a new grpc adapter instance
func New() (adapterx.Cronjob, error) {
	cronjob := newImpl()
	return cronjob, nil
}

// wire.go:

var providerSet = wire.NewSet(newImpl)
