basePath: /api
info:
  contact:
    email: blackhorseya@gmail.com
    name: Sean Zheng
    url: https://blog.seancheng.space
  description: This is a sample server for stringx.
  title: Stringx API
  version: 0.1.0
paths: {}
swagger: "2.0"
