// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package biz is a generated GoMock package.
package biz

import (
	gomock "go.uber.org/mock/gomock"
)

// MockIStringBiz is a mock of IStringBiz interface.
type MockIStringBiz struct {
	ctrl     *gomock.Controller
	recorder *MockIStringBizMockRecorder
}

// MockIStringBizMockRecorder is the mock recorder for MockIStringBiz.
type MockIStringBizMockRecorder struct {
	mock *MockIStringBiz
}

// NewMockIStringBiz creates a new mock instance.
func NewMockIStringBiz(ctrl *gomock.Controller) *MockIStringBiz {
	mock := &MockIStringBiz{ctrl: ctrl}
	mock.recorder = &MockIStringBizMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStringBiz) EXPECT() *MockIStringBizMockRecorder {
	return m.recorder
}
