basePath: /api
definitions:
  endpoints.CreateShortURLRequest:
    properties:
      url:
        type: string
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact:
    email: blackhorseya@gmail.com
    name: Sean Zheng
    url: https://blog.seancheng.space
  description: This is a sample server for shortenurl.
  title: Shortenurl API
  version: 0.1.0
paths:
  /healthz:
    get:
      consumes:
      - application/json
      description: Check the health of the service.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: healthz
      tags:
      - healthz
  /v1/shorten:
    post:
      consumes:
      - application/json
      description: shorten a url
      parameters:
      - description: shorten url request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/endpoints.CreateShortURLRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: Shorten a URL
      tags:
      - shorten
  /v1/shorten/{short_url}:
    get:
      consumes:
      - application/json
      description: get a url
      parameters:
      - description: short url
        in: path
        name: short_url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get a URL
      tags:
      - shorten
swagger: "2.0"
