// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package biz

import (
	mongodb2 "github.com/blackhorseya/monorepo-go/app/ekko/domain/workflow/repo/mongodb"
	"github.com/blackhorseya/monorepo-go/entity/ekko/domain/workflow/biz"
	"github.com/blackhorseya/monorepo-go/pkg/storage/mongodb"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewForExternal() (biz.IWorkflowBiz, error) {
	client, err := mongodb.NewClient()
	if err != nil {
		return nil, err
	}
	iIssueRepo, err := mongodb2.NewIssueRepo(client)
	if err != nil {
		return nil, err
	}
	iWorkflowBiz, err := NewWorkflowBiz(iIssueRepo)
	if err != nil {
		return nil, err
	}
	return iWorkflowBiz, nil
}

// wire.go:

// ProviderSet is biz providers.
var ProviderSet = wire.NewSet(
	NewWorkflowBiz, mongodb2.NewIssueRepo,
)
