// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package mongodb

import (
	"github.com/blackhorseya/monorepo-go/entity/orianna/domain/market/repo"
	"github.com/blackhorseya/monorepo-go/pkg/storage/mongodb"
)

// Injectors from wire.go:

func newForTest() (repo.IStockRepo, error) {
	client, err := mongodb.NewClient()
	if err != nil {
		return nil, err
	}
	iStockRepo, err := NewStockRepo(client)
	if err != nil {
		return nil, err
	}
	return iStockRepo, nil
}
