// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/InfluxCommunity/influxdb3-go/influxdb3"
	"github.com/blackhorseya/monorepo-go/pkg/notify"
	"github.com/blackhorseya/monorepo-go/pkg/storage/influxdb"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, error) {
	notifier, err := notify.NewLineNotifier()
	if err != nil {
		return nil, err
	}
	client, err := influxdb.NewClient()
	if err != nil {
		return nil, err
	}
	mainInjector := &Injector{
		notifier: notifier,
		client:   client,
	}
	return mainInjector, nil
}

// wire.go:

// Injector is the injector for main.
type Injector struct {
	notifier notify.Notifier
	client   *influxdb3.Client
}
