// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package restful

import (
	"github.com/blackhorseya/monorepo-go/pkg/adapterx"
	"github.com/google/wire"
)

// Injectors from wire.go:

// New will create a new restful adapter instance
func New() (adapterx.Restful, error) {
	restful := createRestful()
	return restful, nil
}

// wire.go:

var providerSet = wire.NewSet(createRestful)
