// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package grpc

import (
	"github.com/blackhorseya/monorepo-go/pkg/adapterx"
	"github.com/google/wire"
)

// Injectors from wire.go:

// New will create a new grpc adapter instance
func New() (adapterx.Grpc, error) {
	grpc := newImpl()
	return grpc, nil
}

// wire.go:

var providerSet = wire.NewSet(newImpl)
