# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
          cache: true

      - uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache
        id: cache-bazel
        uses: actions/cache@v3
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: Build
        run: bazel build //...

      - name: Test
        run: bazel test //...

      - name: Login to gcr
        uses: docker/login-action@v2.1.0
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Build and push
        run: |
          make docker-push

  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build
    steps:
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          generateReleaseNotes: true
          prerelease: false
          makeLatest: true
